version: '3'
services:
  web:
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: 'redis:alpine' # Lightweight redis image
