# docker-compose.access.yml
# Usage:
#   docker compose up
version: '3'
services:
  web:
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379
      - BASE_URL=localhost:5000
      - AAI_PK=4951dd81c6854670a21a59696359e7ac

    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - FLASK_APP=app
      - FLASK_ENV=development
      - AAI_PK=4951dd81c6854670a21a59696359e7ac
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: 'redis:alpine' # Lightweight redis image
